server:
#  servlet:
#    context-path: /digital_ticket
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/digital_tickets?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: Mysql_250
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: 127.0.0.1
    password:
    username:
    port: 6379

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      column-format: yyyy-MM-dd HH:mm:ss

  mapper-locations: classpath:/mapper/**/*.xml


jwt:
  header: token
  # 令牌前缀
  token-start-with: Bearer
  # 使用Base64对该令牌进行编码
  base64-secret: gR6cytlUlgMfVh08nLFZf8hMk4abcDX5rWBVlsCbKvRlWcLwNRU6+rIPcLx21x191kJgP8udtoZuHt5yUDWtgg==
  # 令牌过期时间 此处单位秒
  access-token-expiration: 7200   # 两小时
  refresh-token-expiration: 1296000   # 15天
#logging:
#  config: classpath:logback-jwt.xml

wx:
  login:
    appid: wx88cf274021ec5453
    app-secret: 8c90c884b7564235da5dad3e19774f36
    redirect-url:
  pay:
    gateway: https://api.mch.weixin.qq.com/v3/pay/transactions/jsapi
    appid: wx88cf274021ec5453
    mchkey: v4Cuxxab42dBzqg54ApCAdtDDj0BDEXX
    mchid: 1625506813
    type: JSAPI
    notify-url: http://artvery.txwsyun.cn:8080/numshop/orders/notify